baseURL = "https://pythonymous.netlify.app"
DefaultContentLanguage = "en"
title = "Beautiful Hugo"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
